# Daily voter data transformation layer for Good Party analytics
name: "vote_dbt"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "vote_dbt"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  vote_dbt:
    +materialized: view
    +on_schema_change: "fail"
    +tags:
      - goodparty
      - election
      - federal
      - daily
    # Past and Future elction data from MIT and Google's Civic API
    seeds:
      +schema: dim

    # Staging layer - cleaned, standardized data
    stage:
      +schema: stage
      +materialized: view
      +tags:
        - stage

    # Dimension layer - core business entities
    dim:
      +schema: dim
      +materialized: table
      +tags:
        - dim

    # Mart layer - analytics-ready aggregated tables
    mart:
      +schema: mart
      +materialized: table
      +tags:
        - mart

    # Audit layer - data quality and lineage tracking
    audit:
      +schema: audit
      +materialized: view
      +tags:
        - audit
        - monitor

# Global configurations
vars:
  # Current analysis date - can be overridden for historical analysis
  analysis_date: "{{ var('analysis_date', run_started_at.strftime('%Y-%m-%d')) }}"

  # Minimum viable segment size for targeting analysis
  min_segment_size: 10
